const actions = {
  GET_LEADERS: 'GET_LEADERS',
  GET_LEADERS_SUCCESS: 'GET_LEADERS_SUCCESS',
  GET_LEADERS_FAILURE: 'GET_LEADERS_FAILURE',

  CREATE_LEADER: 'CREATE_LEADER',
  CREATE_LEADER_SUCCESS: 'CREATE_LEADER_SUCCESS',
  CREATE_LEADER_FAILURE: 'CREATE_LEADER_FAILURE',
};

export default actions;
